apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: argo
    meta.helm.sh/release-namespace: argo-cd
  creationTimestamp: "2025-09-24T05:29:05Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.1.6
    helm.sh/chart: argo-cd-8.5.4
  name: argo-argocd-server
  namespace: argo-cd
  resourceVersion: "1758691745733343016"
  uid: 02131a3b-e196-4c90-9e1c-1c5288801d04
spec:
  clusterIP: 34.118.230.98
  clusterIPs:
  - 34.118.230.98
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argo
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
