apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater-secret-access
  namespace: argo-cd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["git-creds"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater-secret-access-binding
  namespace: argo-cd
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argo-cd
roleRef:
  kind: Role
  name: argocd-image-updater-secret-access
  apiGroup: rbac.authorization.k8s.io
