apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argo-cd
  # finalizers:
  #   - resources-finalizers.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: nayanzagade7/flask-app:v1.x
    argocd-image-updater.argoproj.io/mywebapp.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/git-creds  
spec:
  project: default

  source:
    repoURL: https://github.com/NAYANZAGADE/argo-cd-image-updater.git
    targetRevision: HEAD
    path: example
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground 
    - PruneLast=true